/* ============================================================
   ESP32 HTTP IoT Server - Access Control System
   Enrollment / Authorization Mode with Fingerprint Simulation

   Hardware:
   - SSD1306 OLED 128x64 (I2C, SDA=21, SCL=22) replaces LEDs
   - Passive buzzer on GPIO 14 for state-change tones
   - WiFi web server on port 80

   Architecture notes:
   - Database layer abstracted behind enrollDB_* helpers
   - Fingerprint sensor calls stubbed in fp_* helpers
   - HTML pages generated by send*Page() functions

   CHANGE LOG (this revision):
   - Authorization system rebuilt with a full state machine:
       waiting_for_scan -> scanning -> processing_scan ->
       verification -> granted / denied -> (alarm after N fails)
   - Authorization page now has a UID text field + a dropdown
     populated from the enrolled-users database, and a
     "Check Authorization" button.
   - Buzzer driver updated to the ESP32 Arduino core v3 ledc
     API (ledcAttach/ledcWriteTone) to match platformio.ini,
     which pins espressif32 @ 7.0.0 (core v3). This is a pure
     internal-implementation fix, not a behavior change, and
     was required for the sketch to compile/run at all on the
     pinned core - the old core v2 calls (ledcSetup /
     ledcAttachPin / ledcDetachPin) no longer exist in core v3.
   - Nothing in the Enrollment system's logic was touched.
     Two shared touch points were required and kept minimal:
       1) updateDisplay() now branches to the new oledShowAuth
          signature for mode 2 only.
       2) the /mode/{} handler now resets the *matching*
          system (enrollReset for mode 1, authReset for mode 2)
          instead of always calling enrollReset().
   ============================================================ */

#include <WiFi.h>
#include <WiFiClient.h>
#include <WebServer.h>
#include <ArduinoJson.h>
#include <uri/UriBraces.h>
#include <Wire.h>
#include <Adafruit_GFX.h>
#include <Adafruit_SSD1306.h>

#define WIFI_SSID     "Wokwi-GUEST"
#define WIFI_PASSWORD ""
#define WIFI_CHANNEL  6

WebServer server(80);

// ── OLED ──────────────────────────────────────────────────
#define SCREEN_WIDTH  128
#define SCREEN_HEIGHT 64
#define OLED_SDA      21
#define OLED_SCL      22
#define OLED_RESET    -1

Adafruit_SSD1306 display(SCREEN_WIDTH, SCREEN_HEIGHT, &Wire, OLED_RESET);

// ── Buzzer ────────────────────────────────────────────────
const int BUZZER_PIN = 14;

// Tone helpers (non-blocking via millis)
// NOTE: your toolchain resolves the core v2 ledc API
// (ledcSetup/ledcAttachPin/ledcWrite/ledcDetachPin), so this
// stays on that API - same as your original code. Function
// names/behavior are unchanged.
unsigned long buzzerUntilMs = 0;
int buzzerFreq = 0;

void buzzerTone(int freq, int durationMs) {
  buzzerFreq    = freq;
  buzzerUntilMs = millis() + durationMs;
  ledcSetup(0, freq, 8);
  ledcAttachPin(BUZZER_PIN, 0);
  ledcWrite(0, 128); // 50% duty cycle
}

void buzzerOff() {
  ledcWrite(0, 0);
  ledcDetachPin(BUZZER_PIN);
  buzzerFreq = 0;
}

void handleBuzzer() {
  if (buzzerFreq > 0 && millis() >= buzzerUntilMs) {
    buzzerOff();
  }
}

// Predefined tones for state changes
void beepScan()    { buzzerTone(1200, 120); }  // short high: scan captured
void beepProcess() { buzzerTone(800,  80);  }  // mid: processing tick
void beepSuccess() { buzzerTone(1800, 300); }  // high long: success
void beepFail()    { buzzerTone(300,  500); }  // low long: failure
void beepMode()    { buzzerTone(1000, 100); }  // mode switch
void beepAuth()    { buzzerTone(1500, 200); }  // auth event
void beepAlarm()   { buzzerTone(2500, 250); }  // sharp alarm chirp

// ── System state ──────────────────────────────────────────
int currentMode = 0; // 0=none, 1=Enrollment, 2=Authorization

// ── Enrollment sub-states ─────────────────────────────────
enum EnrollState {
  ENROLL_IDLE,
  ENROLL_SCAN1_DONE,
  ENROLL_SCAN2_DONE,
  ENROLL_PROCESSING,
  ENROLL_STORING,
  ENROLL_DONE,
  ENROLL_FAILED
};
EnrollState enrollState     = ENROLL_IDLE;
EnrollState prevEnrollState = ENROLL_IDLE;

unsigned long processingStartMs     = 0;
const unsigned long PROCESSING_TIMEOUT_MS = 8000;

// ── In-memory database ────────────────────────────────────
struct EnrolledUser {
  String name;
  String uniqueID;
  unsigned long enrolledAt;
};

const int DB_MAX = 50;
EnrolledUser enrolledDB[DB_MAX];
int dbCount = 0;

// ── Authorization state machine ─────────────────────────────
enum AuthState {
  AUTH_IDLE,          // ready, no check in progress
  AUTH_WAITING_SCAN,  // waiting for scan (starts after button press)
  AUTH_SCANNING,      // scanning the print
  AUTH_PROCESSING,    // processing scan / extracting print
  AUTH_VERIFYING,     // checking id against database
  AUTH_GRANTED,       // authorized access granted
  AUTH_DENIED,        // unauthorized access attempt
  AUTH_ALARM          // too many failed attempts - alarm active
};

AuthState     authState        = AUTH_IDLE;
unsigned long authStateStartMs = 0;
String        authInputUID     = "";

int failedAttempts = 0;
const int MAX_FAILED_ATTEMPTS = 3;

unsigned long alarmStartMs        = 0;
unsigned long lastAlarmBeepMs     = 0;
const unsigned long ALARM_DURATION_MS     = 30000; // alarm resets after 30s
const unsigned long ALARM_BEEP_INTERVAL_MS = 500;

// Simulated timing for each authorization step (ms)
const unsigned long AUTH_WAITING_MS    = 1000;
const unsigned long AUTH_SCANNING_MS   = 700;
const unsigned long AUTH_PROCESSING_MS = 900;
const unsigned long AUTH_VERIFY_MS     = 600;
const unsigned long AUTH_RESULT_HOLD_MS = 3000; // how long granted/denied is shown before idle

// Kept for backward-compatible display/home-page use
bool lastAuthGranted  = false;
bool lastAuthHappened = false;

// Forward declaration - defined later, near the rest of the auth
// state machine, but used earlier by sendHomePage().
String authStateString();

// ──────────────────────────────────────────────────────────
// DATABASE ABSTRACTION LAYER
// ──────────────────────────────────────────────────────────

bool enrollDB_save(const EnrolledUser& user) {
  if (dbCount >= DB_MAX) return false;
  enrolledDB[dbCount++] = user;
  Serial.println("[DB] Saved: " + user.name + " -> " + user.uniqueID);
  return true;
}

String enrollDB_toJSON() {
  String json = "[";
  for (int i = 0; i < dbCount; i++) {
    if (i > 0) json += ",";
    json += "{\"name\":\"" + enrolledDB[i].name
          + "\",\"uid\":\"" + enrolledDB[i].uniqueID
          + "\",\"ts\":"   + String(enrolledDB[i].enrolledAt) + "}";
  }
  json += "]";
  return json;
}

bool enrollDB_findByUID(const String& uid) {
  for (int i = 0; i < dbCount; i++)
    if (enrolledDB[i].uniqueID == uid) return true;
  return false;
}

void enrollDB_clear() {
  dbCount = 0;
  Serial.println("[DB] Cleared.");
}

// ──────────────────────────────────────────────────────────
// FINGERPRINT SENSOR ABSTRACTION LAYER
// ──────────────────────────────────────────────────────────

String fp_template1 = "";
String fp_template2 = "";

void fp_resetTemplates() {
  fp_template1 = "";
  fp_template2 = "";
}

bool fp_captureTemplate1() {
  fp_template1 = "T1_" + String(millis(), HEX);
  return fp_template1.length() > 0;
}

bool fp_captureTemplate2() {
  fp_template2 = "T2_" + String(millis(), HEX);
  return fp_template2.length() > 0;
}

String fp_combineToUID() {
  if (fp_template1.isEmpty() || fp_template2.isEmpty()) return "";
  String uid = "FP-";
  for (int i = 0; i < 4; i++)
    uid += String((fp_template1[i % fp_template1.length()] ^
                   fp_template2[i % fp_template2.length()]), HEX);
  uid.toUpperCase();
  return uid;
}

// ──────────────────────────────────────────────────────────
// OLED DISPLAY
// ──────────────────────────────────────────────────────────

void oledShowEnroll(EnrollState s, const String& name) {
  display.clearDisplay();
  display.setTextColor(SSD1306_WHITE);

  // Header bar
  display.fillRect(0, 0, 128, 12, SSD1306_WHITE);
  display.setTextSize(1);
  display.setTextColor(SSD1306_BLACK);
  display.setCursor(2, 2);
  display.print("ENROLLMENT MODE");
  display.setTextColor(SSD1306_WHITE);

  // Name (truncate if long)
  display.setCursor(2, 16);
  display.setTextSize(1);
  String n = name.length() > 16 ? name.substring(0, 15) + "~" : name;
  display.print(n.length() ? n : "---");

  // State label + progress bar
  String stateLabel;
  int    progW = 0;
  switch (s) {
    case ENROLL_IDLE:       stateLabel = "Ready - Scan 1";  progW = 0;   break;
    case ENROLL_SCAN1_DONE: stateLabel = "Scan 1 OK";       progW = 40;  break;
    case ENROLL_SCAN2_DONE: stateLabel = "Scan 2 OK";       progW = 65;  break;
    case ENROLL_PROCESSING: stateLabel = "Processing...";   progW = 80;  break;
    case ENROLL_STORING:    stateLabel = "Saving...";       progW = 95;  break;
    case ENROLL_DONE:       stateLabel = "ENROLLED!";       progW = 128; break;
    case ENROLL_FAILED:     stateLabel = "FAILED - Retry";  progW = 0;   break;
  }

  display.setCursor(2, 30);
  display.setTextSize(1);
  display.print(stateLabel);

  // Progress bar (at y=44)
  display.drawRect(0, 44, 128, 8, SSD1306_WHITE);
  if (progW > 0)
    display.fillRect(1, 45, progW - 1, 6, SSD1306_WHITE);

  // User count
  display.setCursor(2, 56);
  display.print("Users: ");
  display.print(dbCount);

  display.display();
}

// Rebuilt for the new authorization state machine.
void oledShowAuth(AuthState s, const String& uid, int attempts, unsigned long alarmRemainingSec) {
  display.clearDisplay();
  display.setTextColor(SSD1306_WHITE);

  display.fillRect(0, 0, 128, 12, SSD1306_WHITE);
  display.setTextSize(1);
  display.setTextColor(SSD1306_BLACK);
  display.setCursor(2, 2);
  display.print("AUTH MODE");
  display.setTextColor(SSD1306_WHITE);

  display.setCursor(2, 15);
  display.setTextSize(1);
  String u = uid.length() > 16 ? uid.substring(0, 15) + "~" : uid;
  display.print("ID: ");
  display.print(u.length() ? u : "---");

  String stateLabel;
  switch (s) {
    case AUTH_IDLE:         stateLabel = "Ready";             break;
    case AUTH_WAITING_SCAN: stateLabel = "Waiting for scan";  break;
    case AUTH_SCANNING:     stateLabel = "Scanning...";       break;
    case AUTH_PROCESSING:   stateLabel = "Processing scan";   break;
    case AUTH_VERIFYING:    stateLabel = "Verifying ID...";   break;
    case AUTH_GRANTED:      stateLabel = "";                  break; // shown big below
    case AUTH_DENIED:       stateLabel = "";                  break; // shown big below
    case AUTH_ALARM:        stateLabel = "";                  break; // shown big below
  }

  if (s == AUTH_GRANTED || s == AUTH_DENIED) {
    display.setTextSize(2);
    display.setCursor(s == AUTH_GRANTED ? 12 : 18, 30);
    display.print(s == AUTH_GRANTED ? "GRANTED" : "DENIED");
  } else if (s == AUTH_ALARM) {
    display.setTextSize(2);
    display.setCursor(24, 26);
    display.print("ALARM!");
    display.setTextSize(1);
    display.setCursor(10, 46);
    display.print("Resets in ");
    display.print(alarmRemainingSec);
    display.print("s");
  } else {
    display.setCursor(2, 30);
    display.setTextSize(1);
    display.print(stateLabel);
  }

  display.setCursor(2, 56);
  display.setTextSize(1);
  display.print("Fails:");
  display.print(attempts);
  display.print("/");
  display.print(MAX_FAILED_ATTEMPTS);
  display.print(" Users:");
  display.print(dbCount);

  display.display();
}

void oledShowHome() {
  display.clearDisplay();
  display.setTextColor(SSD1306_WHITE);

  display.fillRect(0, 0, 128, 12, SSD1306_WHITE);
  display.setTextColor(SSD1306_BLACK);
  display.setTextSize(1);
  display.setCursor(2, 2);
  display.print("ACCESS CONTROL");
  display.setTextColor(SSD1306_WHITE);

  display.setCursor(2, 18);
  display.print("Mode: ");
  display.print(currentMode == 0 ? "None" : currentMode == 1 ? "Enrollment" : "Auth");
  display.setCursor(2, 30);
  display.print("Users: ");
  display.print(dbCount);
  display.setCursor(2, 42);
  display.print("IP:");
  display.print(WiFi.localIP().toString());

  display.display();
}

void updateDisplay() {
  if (currentMode == 1) {
    extern String pendingName;
    oledShowEnroll(enrollState, pendingName);
  } else if (currentMode == 2) {
    unsigned long remain = 0;
    if (authState == AUTH_ALARM) {
      unsigned long elapsed = millis() - alarmStartMs;
      remain = (elapsed < ALARM_DURATION_MS) ? (ALARM_DURATION_MS - elapsed) / 1000 : 0;
    }
    oledShowAuth(authState, authInputUID, failedAttempts, remain);
  } else {
    oledShowHome();
  }
}

// ──────────────────────────────────────────────────────────
// SHARED HTML ASSETS  (warm color palette, Google Fonts)
// ──────────────────────────────────────────────────────────

const String CSS_BASE = R"(
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">
<style>
  *{box-sizing:border-box;margin:0;padding:0}
  body{
    font-family:'Inter',sans-serif;
    background:#1a1008;
    color:#e8d5b0;
    min-height:100vh;
    padding:2em 1em;
    display:flex;
    flex-direction:column;
    align-items:center;
  }
  .page-wrap{width:100%;max-width:480px}
  h1{color:#f5a623;font-size:1.4em;font-weight:600;margin-bottom:0.2em;text-align:center}
  h2{color:#e8a045;font-size:1.05em;font-weight:600;margin-bottom:0.6em}
  p{font-size:0.88em;color:#c4a87a;line-height:1.5}
  a.btn{
    display:inline-block;padding:0.55em 1.3em;
    border-radius:8px;text-decoration:none;
    font-size:0.85em;margin:0.3em 0.2em;
    border:1px solid #6b4c1e;color:#e8d5b0;
    background:#2a1a08;font-family:'Inter',sans-serif;
    transition:background 0.15s
  }
  a.btn:hover{background:#3a2510}
  a.btn.active{border-color:#f5a623;color:#f5d08a}
  a.btn.enroll{border-color:#7daf6a;color:#b5dfa8}
  a.btn.auth{border-color:#f0b429;color:#ffe08a}
  a.btn.danger{border-color:#c0614a;color:#e8a090}
  input[type=text],select{
    background:#2a1a08;border:1px solid #6b4c1e;
    color:#e8d5b0;padding:0.55em 0.9em;
    border-radius:6px;font-family:'Inter',sans-serif;
    font-size:0.88em;width:100%;
  }
  input[type=text]:focus,select:focus{outline:none;border-color:#f5a623}
  .card{
    background:#221408;border:1px solid #4a3010;
    border-radius:10px;padding:1.3em;margin:0.9em 0;
  }
  .db-row{
    font-size:0.8em;padding:5px 0;
    border-bottom:1px solid #3a2510;
    display:flex;gap:1em;align-items:center;color:#c4a87a;
    font-family:'JetBrains Mono',monospace;
  }
  .uid{color:#e8953a;font-size:0.72em}
  .screen-box{
    background:#0d0d0d;border:2px solid #4a3010;
    border-radius:8px;padding:1em;
    font-family:'JetBrains Mono',monospace;
    font-size:0.78em;text-align:center;color:#e8c87a;
    margin:0.8em 0;
  }
  .screen-header{
    background:#4a3010;color:#f5d08a;
    font-weight:600;font-size:0.8em;
    padding:3px 8px;border-radius:4px;
    margin-bottom:0.6em;display:inline-block
  }
  .progress{height:5px;background:#3a2510;border-radius:3px;margin:0.8em 0;overflow:hidden}
  .progress-bar{height:100%;background:#f5a623;border-radius:3px;transition:width 0.4s}
  .status-line{
    font-size:0.8em;padding:6px 10px;
    background:#1a1008;border-radius:5px;
    border-left:3px solid #4a3010;margin-bottom:0.8em;
    font-family:'JetBrains Mono',monospace;
  }
  .status-line.scan{border-left-color:#6ab0f5}
  .status-line.proc{border-left-color:#f0a030}
  .status-line.ok  {border-left-color:#7daf6a}
  .status-line.fail{border-left-color:#c0614a}
  form button,button{
    font-family:'Inter',sans-serif;font-size:0.85em;
    padding:0.5em 1.2em;border-radius:7px;
    border:1px solid #6b4c1e;background:#2a1a08;
    color:#e8d5b0;cursor:pointer;transition:background 0.15s
  }
  form button:hover,button:hover{background:#3a2510}
  form button.primary,button.primary{border-color:#f5a623;color:#f5d08a}
  form button.danger,button.danger{border-color:#c0614a;color:#e8a090}
  button:disabled{opacity:0.4;cursor:not-allowed}
  .nav-btns{display:flex;gap:0.5em;justify-content:center;flex-wrap:wrap;margin-bottom:1em}
  .overlay{
    position:fixed;inset:0;background:rgba(0,0,0,0.8);
    display:flex;align-items:center;justify-content:center
  }
  .popup{
    background:#1e1205;border:1px solid #6b4c1e;
    border-radius:12px;padding:2em;width:340px;
  }
  .popup h2{margin-bottom:0.4em;text-align:center}
  .finger-anim{
    width:60px;height:70px;background:#2a1a08;
    border-radius:8px 8px 30px 30px;margin:0.8em auto;
    border:2px solid #6b4c1e;display:flex;
    align-items:center;justify-content:center;
    font-size:2em;
  }
  .popup-actions{display:flex;gap:0.6em;margin-top:0.8em;justify-content:center}
  .mode-indicator{
    text-align:center;font-size:0.8em;
    color:#9a7850;margin-bottom:1em;
    font-family:'JetBrains Mono',monospace;
  }
  .alarm-line{
    margin-top:0.6em;padding:8px 10px;border-radius:6px;
    background:#3a1410;border:1px solid #c0614a;color:#ffb0a0;
    font-weight:600;text-align:center;font-size:0.85em;
  }
</style>
)";

// ──────────────────────────────────────────────────────────
// FORWARD DECLARATION for pendingName (used in updateDisplay)
// ──────────────────────────────────────────────────────────

String pendingName = "";

// ──────────────────────────────────────────────────────────
// PAGE: HOME
// ──────────────────────────────────────────────────────────

void sendHomePage() {
  String modeText = currentMode == 1 ? "Enrollment System"
                  : currentMode == 2 ? "Authorization System"
                  : "None selected";

  String page = "<!DOCTYPE html><html><head><title>ESP32 Access Control</title>" + CSS_BASE + "</head><body>";
  page += "<div class='page-wrap'>";
  page += "<h1>ESP32 Access Control</h1>";
  page += "<div class='mode-indicator'>Mode: " + modeText + " | Users: " + String(dbCount) + "</div>";

  // OLED screen preview
  page += "<div class='screen-box'>";
  page += "<div class='screen-header'>OLED DISPLAY</div><br>";
  if (currentMode == 1) {
    page += "[ ENROLLMENT MODE ]<br>";
    page += "State: " + (enrollState == ENROLL_IDLE ? String("Ready") : String("Active")) + "<br>";
    page += "Users: " + String(dbCount);
  } else if (currentMode == 2) {
    page += "[ AUTH MODE ]<br>";
    page += "Users: " + String(dbCount) + "<br>";
    page += "State: " + authStateString();
  } else {
    page += "[ IDLE ]<br>";
    page += "Select a mode below<br>";
    page += "IP: " + WiFi.localIP().toString();
  }
  page += "</div>";

  page += "<div class='nav-btns'>";
  page += "<a href='/mode/1' class='btn enroll" + String(currentMode==1?" active":"") + "'>Enrollment System</a> ";
  page += "<a href='/mode/2' class='btn auth"   + String(currentMode==2?" active":"") + "'>Authorization System</a>";
  page += "</div>";

  page += "<div class='card'>";
  page += "<h2>Database</h2>";
  page += "<p>Enrolled records: " + String(dbCount) + " / " + String(DB_MAX) + "</p><br>";
  page += "<a href='/api/users' class='btn'>View JSON</a>";
  page += "</div>";
  page += "</div></body></html>";
  server.send(200, "text/html", page);
}

// ──────────────────────────────────────────────────────────
// PAGE: ENROLLMENT SYSTEM  (unchanged)
// ──────────────────────────────────────────────────────────

void sendEnrollmentPage(const String& msg = "", bool isError = false) {
  String page = "<!DOCTYPE html><html><head><title>Enrollment</title>" + CSS_BASE + R"(
  <script>
    function pollState() {
      fetch('/api/enroll/state')
        .then(r => r.json())
        .then(s => {
          updatePopup(s);
          if (s.state !== 'done' && s.state !== 'failed') {
            setTimeout(pollState, 600);
          }
        })
        .catch(() => setTimeout(pollState, 1000));
    }
    function updatePopup(s) {
      const labels = {
        idle:       {title:'Ready',           sub:'Press the button to place finger for scan 1.', prog:0,   cls:'',    icon:'01'},
        scan1_done: {title:'Scan 1 Captured', sub:'Lift finger. Press button for scan 2.',        prog:33,  cls:'scan',icon:'02'},
        scan2_done: {title:'Scan 2 Captured', sub:'Processing - please wait.',                    prog:60,  cls:'scan',icon:'03'},
        processing: {title:'Processing',      sub:'Combining both templates into unique ID...',   prog:75,  cls:'proc',icon:'04'},
        storing:    {title:'Saving to DB',    sub:'Writing fingerprint record to database.',      prog:95,  cls:'ok',  icon:'05'},
        done:       {title:'Enrolled!',       sub:'Success - closing in 2 seconds.',              prog:100, cls:'ok',  icon:'06'},
        failed:     {title:'Failed',          sub:'Timed out or error. Press Retry to try again.',prog:0,  cls:'fail',icon:'07'},
      };
      const info = labels[s.state] || labels['idle'];
      document.getElementById('popTitle').textContent = info.title;
      document.getElementById('popSub').textContent   = info.sub;
      document.getElementById('progBar').style.width  = info.prog + '%';
      const sl = document.getElementById('statusLine');
      sl.textContent = 'state: ' + s.state;
      sl.className   = 'status-line ' + info.cls;

      const btn = document.getElementById('scanBtn');
      btn.disabled = false;

      if (s.state === 'idle') {
        btn.textContent = 'Scan 1 - Place Finger';
        btn.onclick = () => fetch('/api/enroll/scan1').then(() => pollState());
      } else if (s.state === 'scan1_done') {
        btn.textContent = 'Scan 2 - Place Finger';
        btn.onclick = () => fetch('/api/enroll/scan2').then(() => pollState());
      } else if (s.state === 'scan2_done' || s.state === 'processing' || s.state === 'storing') {
        btn.textContent = 'Processing...';
        btn.disabled = true;
      } else if (s.state === 'failed') {
        btn.textContent = 'Retry';
        btn.onclick = () => fetch('/api/enroll/reset').then(() => pollState());
      } else {
        btn.textContent = '...';
        btn.disabled = true;
      }

      if (s.state === 'done') { setTimeout(closePopup, 2000); }
    }
    function openPopup(name) {
      if (!name.trim()) { alert('Enter a name first.'); return; }
      fetch('/api/enroll/start?name=' + encodeURIComponent(name))
        .then(() => {
          document.getElementById('overlay').style.display = 'flex';
          pollState();
        });
    }
    function closePopup() {
      fetch('/api/enroll/reset');
      document.getElementById('overlay').style.display = 'none';
      location.reload();
    }
  </script>
  )" + "</head><body>";

  page += "<div class='page-wrap'>";
  page += "<h1>Enrollment System</h1>";
  page += "<div class='mode-indicator'>OLED: G+R on | Buzzer: beep on scan</div>";

  page += "<div class='card'>";
  page += "<h2>New Enrollment</h2>";
  if (msg.length()) {
    page += "<p style='color:" + String(isError ? "#e8a090" : "#b5dfa8") + ";margin-bottom:0.8em'>" + msg + "</p>";
  }
  page += "<input type='text' id='nameField' placeholder='Full name' /><br><br>";
  page += "<button class='primary' onclick='openPopup(document.getElementById(\"nameField\").value)'>Enroll Fingerprint</button>";
  page += "</div>";

  page += "<div class='card'><h2>Enrolled Users (" + String(dbCount) + ")</h2>";
  if (dbCount == 0) {
    page += "<p style='color:#6a5030'>No records yet.</p>";
  } else {
    for (int i = 0; i < dbCount; i++) {
      page += "<div class='db-row'><span>" + enrolledDB[i].name + "</span>"
              "<span class='uid'>" + enrolledDB[i].uniqueID + "</span></div>";
    }
  }
  page += "<br><a href='/api/db/clear' onclick=\"return confirm('Clear all records?')\" class='btn danger'>Clear Database</a>";
  page += "</div>";

  page += "<div class='nav-btns'>";
  page += "<a href='/' class='btn'>Home</a>";
  page += "<a href='/mode/2' class='btn auth'>Switch to Auth</a>";
  page += "</div>";

  // Popup overlay
  page += R"(
  <div class='overlay' id='overlay' style='display:none'>
    <div class='popup'>
      <h2 id='popTitle'>Idle</h2>
      <p id='popSub' style='font-size:0.82em;color:#c4a87a;margin-bottom:0.6em;text-align:center'>Waiting...</p>
      <div class='finger-anim' id='fingerAnim'>~</div>
      <div class='progress'><div class='progress-bar' id='progBar' style='width:0'></div></div>
      <div class='status-line' id='statusLine'>state: idle</div>
      <div class='popup-actions'>
        <button id='scanBtn' class='primary'>Scan 1 - Place Finger</button>
        <button onclick='closePopup()'>Cancel</button>
      </div>
    </div>
  </div>)";

  page += "<script>document.getElementById('scanBtn').onclick = () => fetch('/api/enroll/scan1').then(() => pollState());</script>";
  page += "</div></body></html>";
  server.send(200, "text/html", page);
}

// ──────────────────────────────────────────────────────────
// PAGE: AUTHORIZATION SYSTEM  (rebuilt)
// ──────────────────────────────────────────────────────────

void sendAuthorizationPage() {
  String page = "<!DOCTYPE html><html><head><title>Authorization</title>" + CSS_BASE + R"(
  <script>
    const stateLabels = {
      idle:         {title:'Ready',              cls:''},
      waiting_scan: {title:'Waiting for scan...',cls:'scan'},
      scanning:     {title:'Scanning...',        cls:'scan'},
      processing:   {title:'Processing scan...', cls:'proc'},
      verifying:    {title:'Verifying ID...',    cls:'proc'},
      granted:      {title:'ACCESS GRANTED',     cls:'ok'},
      denied:       {title:'ACCESS DENIED',      cls:'fail'},
      alarm:        {title:'ALARM ACTIVE',       cls:'fail'},
    };
    const busyStates = ['waiting_scan','scanning','processing','verifying'];

    function loadUsers() {
      fetch('/api/users').then(r => r.json()).then(list => {
        const sel = document.getElementById('uidSelect');
        sel.innerHTML = "<option value=''>-- select enrolled ID --</option>";
        list.forEach(u => {
          const opt = document.createElement('option');
          opt.value = u.uid;
          opt.textContent = u.name + ' (' + u.uid + ')';
          sel.appendChild(opt);
        });
      });
    }
    function fillFromSelect() {
      const sel = document.getElementById('uidSelect');
      if (sel.value) document.getElementById('uidField').value = sel.value;
    }
    function checkAuth() {
      const uid = document.getElementById('uidField').value.trim();
      if (!uid) { alert('Enter or select a UID first.'); return; }
      document.getElementById('checkBtn').disabled = true;
      fetch('/api/auth/check?uid=' + encodeURIComponent(uid));
    }
    function pollAuth() {
      fetch('/api/auth/state').then(r => r.json()).then(s => {
        const info = stateLabels[s.state] || stateLabels['idle'];
        const box = document.getElementById('authResult');
        box.textContent = info.title;
        box.className = 'status-line ' + info.cls;

        document.getElementById('attemptsLine').textContent =
          'Failed attempts: ' + s.attempts + ' / ' + s.maxAttempts;

        const alarmLine = document.getElementById('alarmLine');
        if (s.state === 'alarm') {
          alarmLine.style.display = 'block';
          alarmLine.textContent = 'ALARM ACTIVE - auto-resets in ' + s.alarmRemaining + 's';
        } else {
          alarmLine.style.display = 'none';
        }

        const btn = document.getElementById('checkBtn');
        btn.disabled = busyStates.includes(s.state) || s.state === 'alarm';

        setTimeout(pollAuth, 500);
      }).catch(() => setTimeout(pollAuth, 1000));
    }
    window.onload = () => { loadUsers(); pollAuth(); };
  </script>
  )" + "</head><body>";

  page += "<div class='page-wrap'>";
  page += "<h1>Authorization System</h1>";
  page += "<div class='mode-indicator'>OLED: state + attempts | Buzzer: beep per step, alarm on lockout</div>";

  page += "<div class='card'>";
  page += "<h2>Verify Access</h2>";
  page += "<p>Select an enrolled ID from the list below, or type it in manually, then press Check Authorization.</p><br>";
  page += "<select id='uidSelect' onchange='fillFromSelect()'></select><br><br>";
  page += "<input type='text' id='uidField' placeholder='Unique ID (e.g. FP-A1B2)' /><br><br>";
  page += "<button id='checkBtn' class='primary' onclick='checkAuth()'>Check Authorization</button>";
  page += "<p style='margin-top:0.6em;color:#9a7850;font-size:0.8em'>Enrolled users: " + String(dbCount) + "</p>";
  page += "<div id='authResult' class='status-line' style='margin-top:0.8em;text-align:center;font-size:0.95em'>Ready</div>";
  page += "<p id='attemptsLine' style='font-size:0.78em;color:#9a7850'></p>";
  page += "<div id='alarmLine' class='alarm-line' style='display:none'></div>";
  page += "</div>";

  page += "<div class='nav-btns'>";
  page += "<a href='/' class='btn'>Home</a>";
  page += "<a href='/mode/1' class='btn enroll'>Switch to Enrollment</a>";
  page += "</div>";
  page += "</div></body></html>";
  server.send(200, "text/html", page);
}

// ──────────────────────────────────────────────────────────
// ENROLLMENT STATE MACHINE  (unchanged)
// ──────────────────────────────────────────────────────────

void enrollStart(const String& name) {
  pendingName = name;
  fp_resetTemplates();
  enrollState = ENROLL_IDLE;
  processingStartMs = 0;
  updateDisplay();
  Serial.println("[Enroll] Started for: " + name);
}

void enrollScan1() {
  if (enrollState != ENROLL_IDLE) return;
  if (fp_captureTemplate1()) {
    enrollState = ENROLL_SCAN1_DONE;
    beepScan();
    updateDisplay();
    Serial.println("[Enroll] Template 1 captured: " + fp_template1);
  }
}

void enrollScan2() {
  if (enrollState != ENROLL_SCAN1_DONE) return;
  if (fp_captureTemplate2()) {
    enrollState = ENROLL_SCAN2_DONE;
    processingStartMs = millis();
    beepScan();
    updateDisplay();
    Serial.println("[Enroll] Template 2 captured: " + fp_template2);
  }
}

void enrollProcessLoop() {
  if (enrollState == ENROLL_SCAN2_DONE) {
    unsigned long elapsed = millis() - processingStartMs;
    if (elapsed > PROCESSING_TIMEOUT_MS) {
      enrollState = ENROLL_FAILED;
      beepFail();
      updateDisplay();
      Serial.println("[Enroll] FAILED - processing timeout");
      return;
    }
    if (elapsed > 1500) {
      enrollState = ENROLL_PROCESSING;
      beepProcess();
      updateDisplay();
    }
  }
  if (enrollState == ENROLL_PROCESSING) {
    unsigned long elapsed = millis() - processingStartMs;
    if (elapsed > 3000) {
      String uid = fp_combineToUID();
      if (uid.isEmpty()) {
        enrollState = ENROLL_FAILED;
        beepFail();
        updateDisplay();
        return;
      }
      enrollState = ENROLL_STORING;
      updateDisplay();
      EnrolledUser u;
      u.name       = pendingName;
      u.uniqueID   = uid;
      u.enrolledAt = millis();
      if (enrollDB_save(u)) {
        enrollState = ENROLL_DONE;
        beepSuccess();
        updateDisplay();
        Serial.println("[Enroll] DONE - " + u.name + " -> " + u.uniqueID);
      } else {
        enrollState = ENROLL_FAILED;
        beepFail();
        updateDisplay();
        Serial.println("[Enroll] FAILED - database full");
      }
    }
  }
}

void enrollReset() {
  fp_resetTemplates();
  pendingName = "";
  enrollState = ENROLL_IDLE;
  updateDisplay();
}

String enrollStateString() {
  switch (enrollState) {
    case ENROLL_IDLE:       return "idle";
    case ENROLL_SCAN1_DONE: return "scan1_done";
    case ENROLL_SCAN2_DONE: return "scan2_done";
    case ENROLL_PROCESSING: return "processing";
    case ENROLL_STORING:    return "storing";
    case ENROLL_DONE:       return "done";
    case ENROLL_FAILED:     return "failed";
  }
  return "unknown";
}

// ──────────────────────────────────────────────────────────
// AUTHORIZATION STATE MACHINE  (new)
// ──────────────────────────────────────────────────────────

String authStateString() {
  switch (authState) {
    case AUTH_IDLE:         return "idle";
    case AUTH_WAITING_SCAN: return "waiting_scan";
    case AUTH_SCANNING:     return "scanning";
    case AUTH_PROCESSING:   return "processing";
    case AUTH_VERIFYING:    return "verifying";
    case AUTH_GRANTED:      return "granted";
    case AUTH_DENIED:       return "denied";
    case AUTH_ALARM:        return "alarm";
  }
  return "unknown";
}

// Kicks off a check. Ignored if a check is already running or the
// system is in an active alarm lockdown.
void authCheck(const String& uid) {
  if (authState == AUTH_WAITING_SCAN || authState == AUTH_SCANNING ||
      authState == AUTH_PROCESSING   || authState == AUTH_VERIFYING ||
      authState == AUTH_ALARM) {
    return;
  }
  if (uid.isEmpty()) return;

  authInputUID     = uid;
  authState        = AUTH_WAITING_SCAN;
  authStateStartMs = millis();
  lastAuthHappened = false;
  updateDisplay();
  Serial.println("[Auth] Check started for UID: " + uid);
}

void authReset() {
  authState        = AUTH_IDLE;
  authInputUID     = "";
  lastAuthHappened = false;
  updateDisplay();
}

// Repeated chirp while the alarm is active (non-blocking).
void handleAlarmBuzzer(unsigned long now) {
  if (now - lastAlarmBeepMs >= ALARM_BEEP_INTERVAL_MS) {
    lastAlarmBeepMs = now;
    beepAlarm();
  }
}

void authProcessLoop() {
  unsigned long now = millis();

  switch (authState) {
    case AUTH_WAITING_SCAN:
      if (now - authStateStartMs >= AUTH_WAITING_MS) {
        authState = AUTH_SCANNING;
        authStateStartMs = now;
        beepScan();
        updateDisplay();
      }
      break;

    case AUTH_SCANNING:
      if (now - authStateStartMs >= AUTH_SCANNING_MS) {
        authState = AUTH_PROCESSING;
        authStateStartMs = now;
        beepProcess();
        updateDisplay();
      }
      break;

    case AUTH_PROCESSING:
      if (now - authStateStartMs >= AUTH_PROCESSING_MS) {
        authState = AUTH_VERIFYING;
        authStateStartMs = now;
        updateDisplay();
      }
      break;

    case AUTH_VERIFYING:
      if (now - authStateStartMs >= AUTH_VERIFY_MS) {
        bool found = enrollDB_findByUID(authInputUID);
        lastAuthHappened = true;
        lastAuthGranted  = found;

        if (found) {
          authState = AUTH_GRANTED;
          failedAttempts = 0;
          beepSuccess();
          Serial.println("[Auth] GRANTED for UID: " + authInputUID);
        } else {
          authState = AUTH_DENIED;
          failedAttempts++;
          beepFail();
          Serial.println("[Auth] DENIED for UID: " + authInputUID +
                          " (fail " + String(failedAttempts) + "/" + String(MAX_FAILED_ATTEMPTS) + ")");

          if (failedAttempts >= MAX_FAILED_ATTEMPTS) {
            authState      = AUTH_ALARM;
            alarmStartMs   = now;
            lastAlarmBeepMs = now - ALARM_BEEP_INTERVAL_MS; // fire immediately
            Serial.println("[Auth] ALARM triggered - too many failed attempts");
          }
        }
        authStateStartMs = now;
        updateDisplay();
      }
      break;

    case AUTH_GRANTED:
    case AUTH_DENIED:
      if (now - authStateStartMs >= AUTH_RESULT_HOLD_MS) {
        authState = AUTH_IDLE;
        updateDisplay();
      }
      break;

    case AUTH_ALARM:
      handleAlarmBuzzer(now);
      if (now - alarmStartMs >= ALARM_DURATION_MS) {
        authState      = AUTH_IDLE;
        failedAttempts = 0;
        buzzerOff();
        Serial.println("[Auth] Alarm reset after timeout");
        updateDisplay();
      }
      break;

    default:
      break;
  }
}

// ──────────────────────────────────────────────────────────
// SETUP
// ──────────────────────────────────────────────────────────

void setup() {
  Serial.begin(115200);

  // Buzzer
  pinMode(BUZZER_PIN, OUTPUT);

  // OLED
  Wire.begin(OLED_SDA, OLED_SCL);
  if (!display.begin(SSD1306_SWITCHCAPVCC, 0x3C)) {
    Serial.println("[OLED] Not found — check wiring");
  } else {
    display.clearDisplay();
    display.setTextColor(SSD1306_WHITE);
    display.setTextSize(1);
    display.setCursor(10, 28);
    display.print("Connecting WiFi...");
    display.display();
  }

  // WiFi
  WiFi.begin(WIFI_SSID, WIFI_PASSWORD, WIFI_CHANNEL);
  Serial.print("Connecting to WiFi");
  while (WiFi.status() != WL_CONNECTED) { delay(100); Serial.print("."); }
  Serial.println(" Connected! IP: " + WiFi.localIP().toString());

  display.clearDisplay();
  display.setCursor(2, 20);
  display.print("Connected!");
  display.setCursor(2, 36);
  display.setTextSize(1);
  display.print(WiFi.localIP().toString());
  display.display();
  delay(1500);

  // ── Page routes ─────────────────────────────────────────
  server.on("/", sendHomePage);

  server.on(UriBraces("/mode/{}"), []() {
    int m = server.pathArg(0).toInt();
    if (m == 1 || m == 2) {
      currentMode = m;
      if (m == 1) enrollReset();
      else        authReset();
      beepMode();
      updateDisplay();
      Serial.println("[Mode] -> " + String(m == 1 ? "Enrollment" : "Authorization"));
    }
    if (currentMode == 1)      sendEnrollmentPage();
    else if (currentMode == 2) sendAuthorizationPage();
    else                       sendHomePage();
  });

  // ── Enrollment REST API  (unchanged) ─────────────────────
  server.on("/api/enroll/start", []() {
    String name = server.arg("name");
    if (name.isEmpty()) { server.send(400, "text/plain", "name required"); return; }
    enrollStart(name);
    server.send(200, "application/json", "{\"ok\":true}");
  });

  server.on("/api/enroll/scan1", []() {
    enrollScan1();
    server.send(200, "application/json",
      "{\"state\":\"" + enrollStateString() + "\"}");
  });

  server.on("/api/enroll/scan2", []() {
    enrollScan2();
    server.send(200, "application/json",
      "{\"state\":\"" + enrollStateString() + "\"}");
  });

  server.on("/api/enroll/state", []() {
    server.send(200, "application/json",
      "{\"state\":\"" + enrollStateString() + "\",\"name\":\"" + pendingName + "\"}");
  });

  server.on("/api/enroll/reset", []() {
    enrollReset();
    server.send(200, "application/json", "{\"ok\":true}");
  });

  // ── Database API  (unchanged) ────────────────────────────
  server.on("/api/users", []() {
    server.send(200, "application/json", enrollDB_toJSON());
  });

  server.on("/api/db/clear", []() {
    enrollDB_clear();
    server.sendHeader("Location", "/mode/1");
    server.send(302);
  });

  // ── Authorization REST API  (new) ────────────────────────
  server.on("/api/auth/check", []() {
    String uid = server.arg("uid");
    if (uid.isEmpty()) { server.send(400, "application/json", "{\"error\":\"uid required\"}"); return; }
    authCheck(uid);
    server.send(200, "application/json", "{\"ok\":true,\"state\":\"" + authStateString() + "\"}");
  });

  server.on("/api/auth/state", []() {
    unsigned long remain = 0;
    if (authState == AUTH_ALARM) {
      unsigned long elapsed = millis() - alarmStartMs;
      remain = (elapsed < ALARM_DURATION_MS) ? (ALARM_DURATION_MS - elapsed) / 1000 : 0;
    }
    String json = "{";
    json += "\"state\":\""    + authStateString() + "\",";
    json += "\"uid\":\""      + authInputUID + "\",";
    json += "\"attempts\":"   + String(failedAttempts) + ",";
    json += "\"maxAttempts\":"+ String(MAX_FAILED_ATTEMPTS) + ",";
    json += "\"alarmRemaining\":" + String(remain) + ",";
    json += "\"granted\":"    + String(lastAuthGranted  ? "true" : "false") + ",";
    json += "\"happened\":"   + String(lastAuthHappened ? "true" : "false");
    json += "}";
    server.send(200, "application/json", json);
  });

  server.on("/api/auth/reset", []() {
    authReset();
    server.send(200, "application/json", "{\"ok\":true}");
  });

  server.begin();
  currentMode = 1;
  updateDisplay();
  Serial.println("[HTTP] Server started — http://localhost:8180");
}

// ──────────────────────────────────────────────────────────
// LOOP
// ──────────────────────────────────────────────────────────

void loop() {
  server.handleClient();
  enrollProcessLoop();
  authProcessLoop();
  handleBuzzer();
  delay(2);
}