/* ============================================================
   ESP32 HTTP IoT Server — Access Control System
   Enrollment / Authorization Mode with Fingerprint Simulation

   Architecture notes (for future migration):
   - Database layer is abstracted behind enrollDB_* helpers
     → swap in MongoDB/REST calls without touching UI logic
   - Fingerprint sensor calls are stubbed in fp_* helpers
     → replace with actual FPS library (e.g. Adafruit_Fingerprint)
   - All HTML pages are generated by send*Page() functions
     → can be replaced with a real frontend (React / Vue) later
   ============================================================ */

#include <WiFi.h>
#include <WiFiClient.h>
#include <WebServer.h>
#include <ArduinoJson.h>   // add to platformio.ini / library manager
#include <uri/UriBraces.h>

#define WIFI_SSID     "Wokwi-GUEST"
#define WIFI_PASSWORD ""
#define WIFI_CHANNEL  6

WebServer server(80);

// ── GPIO ──────────────────────────────────────────────────
const int LED_GREEN  = 25;
const int LED_RED    = 26;
const int LED_YELLOW = 27;

// ── System state ──────────────────────────────────────────
// 0 = none, 1 = Enrollment, 2 = Authorization
int currentMode = 0;

// ── Enrollment sub-states ─────────────────────────────────
enum EnrollState {
  ENROLL_IDLE,        // waiting for user to trigger scan 1
  ENROLL_SCAN1_DONE,  // scan 1 captured, waiting for user to trigger scan 2
  ENROLL_SCAN2_DONE,  // scan 2 captured, processing starts automatically in loop()
  ENROLL_PROCESSING,  // firmware combining templates
  ENROLL_STORING,     // writing to database
  ENROLL_DONE,        // success
  ENROLL_FAILED       // timeout or error
};
EnrollState enrollState = ENROLL_IDLE;

unsigned long processingStartMs = 0;
const unsigned long PROCESSING_TIMEOUT_MS = 8000; // fail if > 8 s

// ── In-memory database (replace with MongoDB later) ───────
// Flexible struct — add fields (card ID, role, etc.) freely
struct EnrolledUser {
  String name;
  String uniqueID;   // combined fingerprint hash/ID
  unsigned long enrolledAt; // millis timestamp
};

const int DB_MAX = 50;
EnrolledUser enrolledDB[DB_MAX];
int dbCount = 0;

// ──────────────────────────────────────────────────────────
// DATABASE ABSTRACTION LAYER
// Swap these four functions for HTTP/MongoDB calls later.
// ──────────────────────────────────────────────────────────

bool enrollDB_save(const EnrolledUser& user) {
  if (dbCount >= DB_MAX) return false;
  enrolledDB[dbCount++] = user;
  Serial.println("[DB] Saved: " + user.name + " → " + user.uniqueID);
  return true;
}

String enrollDB_toJSON() {
  // Returns a JSON array for the /api/users endpoint
  String json = "[";
  for (int i = 0; i < dbCount; i++) {
    if (i > 0) json += ",";
    json += "{\"name\":\"" + enrolledDB[i].name
          + "\",\"uid\":\"" + enrolledDB[i].uniqueID
          + "\",\"ts\":" + String(enrolledDB[i].enrolledAt) + "}";
  }
  json += "]";
  return json;
}

bool enrollDB_findByUID(const String& uid) {
  for (int i = 0; i < dbCount; i++)
    if (enrolledDB[i].uniqueID == uid) return true;
  return false;
}

void enrollDB_clear() {
  dbCount = 0;
  Serial.println("[DB] Cleared.");
}

// ──────────────────────────────────────────────────────────
// FINGERPRINT SENSOR ABSTRACTION LAYER
// Replace these stubs with your actual sensor library.
// e.g. #include <Adafruit_Fingerprint.h>
// ──────────────────────────────────────────────────────────

String fp_template1 = "";
String fp_template2 = "";

void fp_resetTemplates() {
  fp_template1 = "";
  fp_template2 = "";
}

bool fp_captureTemplate1() {
  // Real: sensor.getImage(), sensor.image2Tz(1)
  // Simulate a raw template string
  fp_template1 = "T1_" + String(millis(), HEX);
  return fp_template1.length() > 0;
}

bool fp_captureTemplate2() {
  // Real: sensor.getImage(), sensor.image2Tz(2)
  fp_template2 = "T2_" + String(millis(), HEX);
  return fp_template2.length() > 0;
}

String fp_combineToUID() {
  // Real: sensor.createModel() then export model bytes and hash
  // Simulate: XOR-like mix of both template strings
  if (fp_template1.isEmpty() || fp_template2.isEmpty()) return "";
  String uid = "FP-";
  for (int i = 0; i < 4; i++)
    uid += String((fp_template1[i % fp_template1.length()] ^
                   fp_template2[i % fp_template2.length()]), HEX);
  uid.toUpperCase();
  return uid;
}

// ──────────────────────────────────────────────────────────
// LED HELPERS
// ──────────────────────────────────────────────────────────

void ledsOff() {
  digitalWrite(LED_GREEN,  LOW);
  digitalWrite(LED_RED,    LOW);
  digitalWrite(LED_YELLOW, LOW);
}

// State → LED pattern mapping
// Blinking is approximated in-firmware; finer patterns need a timer ISR.
void ledSet(bool g, bool r, bool y) {
  digitalWrite(LED_GREEN,  g ? HIGH : LOW);
  digitalWrite(LED_RED,    r ? HIGH : LOW);
  digitalWrite(LED_YELLOW, y ? HIGH : LOW);
}

void updateLeds() {
  if (currentMode == 1) {
    switch (enrollState) {
      case ENROLL_IDLE:       ledSet(1,1,0); break; // G+R solid — ready
      case ENROLL_SCAN1_DONE: ledSet(1,0,0); break; // G solid — scan 1 done
      case ENROLL_SCAN2_DONE: ledSet(0,1,0); break; // R solid — scan 2 done, processing starting
      case ENROLL_PROCESSING: ledSet(1,1,0); break; // G+R — will blink in handleBlinkLeds()
      case ENROLL_STORING:    ledSet(1,1,1); break; // all on — storing
      case ENROLL_DONE:       ledSet(1,0,0); break; // G only — success
      case ENROLL_FAILED:     ledSet(0,1,0); break; // R only — will blink in handleBlinkLeds()
    }
  } else if (currentMode == 2) {
    ledSet(0,0,1);
  } else {
    ledsOff();
  }
}

unsigned long lastBlinkMs = 0;
bool blinkOn = false;
void handleBlinkLeds() {
  if (currentMode != 1) return;
  if (enrollState != ENROLL_PROCESSING && enrollState != ENROLL_FAILED) return;
  if (millis() - lastBlinkMs < 400) return;
  lastBlinkMs = millis();
  blinkOn = !blinkOn;
  if (enrollState == ENROLL_PROCESSING) {
    ledSet(blinkOn, blinkOn, 0); // G+R alternating blink
  } else if (enrollState == ENROLL_FAILED) {
    ledSet(0, blinkOn, 0);       // R blink only
  }
}

// ──────────────────────────────────────────────────────────
// SHARED HTML ASSETS
// ──────────────────────────────────────────────────────────

const String CSS_BASE = R"(
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
  *{box-sizing:border-box}
  body{font-family:'Courier New',monospace;background:#111;color:#ccc;margin:0;padding:2em;min-height:100vh}
  h1{color:#90caf9;font-size:1.3em;margin-bottom:0.2em}
  h2{color:#80cbc4;font-size:1.1em;margin-bottom:0.4em}
  p{font-size:0.9em;color:#aaa}
  a.btn{display:inline-block;padding:0.6em 1.3em;border-radius:6px;text-decoration:none;
         font-size:0.9em;margin:0.4em 0.2em;border:1px solid #444;color:#ccc;background:#1e1e1e}
  a.btn:hover{background:#2a2a2a}
  a.btn.active{border-color:#42a5f5;color:#90caf9}
  a.btn.enroll{border-color:#66bb6a;color:#a5d6a7}
  a.btn.auth{border-color:#ffca28;color:#ffe082}
  input[type=text]{background:#1e1e1e;border:1px solid #444;color:#ccc;
    padding:0.5em 0.8em;border-radius:4px;font-family:inherit;font-size:0.9em;width:100%;max-width:280px}
  .led-row{display:flex;gap:1.2em;margin:1em 0;align-items:center;font-size:0.8em}
  .dot{width:16px;height:16px;border-radius:50%;display:inline-block;vertical-align:middle}
  .card{background:#1a1a1a;border:1px solid #333;border-radius:8px;padding:1.2em;margin:1em 0;max-width:440px}
  .db-row{font-size:0.8em;padding:4px 0;border-bottom:1px solid #2a2a2a;display:flex;gap:1em;color:#aaa}
  .uid{color:#64b5f6;font-size:0.75em}
  .state-badge{font-size:0.75em;padding:2px 8px;border-radius:10px;display:inline-block;margin-left:0.5em}
  /* Popup overlay */
  .overlay{position:fixed;inset:0;background:rgba(0,0,0,0.75);display:flex;
            align-items:center;justify-content:center}
  .popup{background:#1a1a1a;border:1px solid #444;border-radius:10px;padding:2em;width:340px}
  .popup h2{margin-bottom:0.3em}
  .finger-svg{display:block;margin:1em auto;opacity:0.6}
  .progress{height:4px;background:#333;border-radius:2px;margin:1em 0;overflow:hidden}
  .progress-bar{height:100%;background:#42a5f5;border-radius:2px;transition:width 0.4s}
  .status-line{font-size:0.8em;padding:6px 10px;background:#111;border-radius:4px;
                border-left:3px solid #444;margin-bottom:0.8em}
  .status-line.scan{border-left-color:#42a5f5}
  .status-line.proc{border-left-color:#ff9800}
  .status-line.ok  {border-left-color:#4caf50}
  .status-line.fail{border-left-color:#f44336}
  form button,button{font-family:inherit;font-size:0.85em;padding:0.5em 1.1em;
    border-radius:5px;border:1px solid #444;background:#1e1e1e;color:#ccc;cursor:pointer}
  form button:hover,button:hover{background:#2a2a2a}
  form button.primary{border-color:#42a5f5;color:#90caf9}
  form button.danger{border-color:#e57373;color:#ef9a9a}
</style>
)";

// ──────────────────────────────────────────────────────────
// PAGE: HOME
// ──────────────────────────────────────────────────────────

void sendHomePage() {
  String modeText = currentMode == 1 ? "Enrollment System"
                  : currentMode == 2 ? "Authorization System"
                  : "None selected";

  String page = "<!DOCTYPE html><html><head><title>ESP32 Access Control</title>" + CSS_BASE + "</head><body>";
  page += "<h1>ESP32 Access Control System</h1>";
  page += "<p>Current mode: <b>" + modeText + "</b></p>";
  page += "<div class='led-row'>";
  page += "<span class='dot' style='background:" + String(currentMode==1?"#4caf50":"#333") + "'></span> Green ";
  page += "<span class='dot' style='background:" + String(currentMode==1?"#f44336":"#333") + "'></span> Red ";
  page += "<span class='dot' style='background:" + String(currentMode==2?"#ffeb3b":"#333") + "'></span> Yellow";
  page += "</div>";
  page += "<div>";
  page += "<a href='/mode/1' class='btn enroll" + String(currentMode==1?" active":"") + "'>Enrollment System</a> ";
  page += "<a href='/mode/2' class='btn auth"   + String(currentMode==2?" active":"") + "'>Authorization System</a>";
  page += "</div>";
  page += "<div class='card'><p style='font-size:0.8em;color:#666'>Enrolled users: " + String(dbCount) + "</p>";
  page += "<a href='/api/users' class='btn'>View DB (JSON)</a></div>";
  page += "</body></html>";
  server.send(200, "text/html", page);
}

// ──────────────────────────────────────────────────────────
// PAGE: ENROLLMENT SYSTEM
// ──────────────────────────────────────────────────────────

void sendEnrollmentPage(const String& msg = "", bool isError = false) {
  String page = "<!DOCTYPE html><html><head><title>Enrollment</title>" + CSS_BASE + R"(
  <script>
    // Periodically poll enrollment state from /api/enroll/state
    // so the popup updates without a full page reload.
    // In a real frontend (React) this would be a WebSocket or SSE stream.
    function pollState() {
      fetch('/api/enroll/state')
        .then(r => r.json())
        .then(s => {
          updatePopup(s);
          if (s.state !== 'done' && s.state !== 'failed') {
            setTimeout(pollState, 600);
          }
        })
        .catch(() => setTimeout(pollState, 1000));
    }
    function updatePopup(s) {
      // State name convention:
      //   idle       = waiting for scan 1 button press
      //   scan1_done = scan 1 captured, waiting for scan 2 button press
      //   scan2_done = scan 2 captured, processing running automatically
      //   processing = firmware combining templates (no user action needed)
      //   storing    = writing to DB  (no user action needed)
      //   done       = success
      //   failed     = timeout or error
      const labels = {
        idle:       {title:'Ready',          sub:'Press the button to place finger for scan 1.', prog:0,   cls:''},
        scan1_done: {title:'Scan 1 captured',sub:'Lift finger. Press button to place for scan 2.',prog:33, cls:'scan'},
        scan2_done: {title:'Scan 2 captured',sub:'Processing — please wait.',                   prog:60,  cls:'scan'},
        processing: {title:'Processing',     sub:'Combining both templates into unique ID...',   prog:75,  cls:'proc'},
        storing:    {title:'Storing',        sub:'Writing fingerprint record to database.',      prog:95,  cls:'ok'},
        done:       {title:'Enrolled!',      sub:'Success — closing in 2 seconds.',             prog:100, cls:'ok'},
        failed:     {title:'Failed',         sub:'Timed out or error. Press Retry to try again.',prog:0,  cls:'fail'},
      };
      const info = labels[s.state] || labels['idle'];
      document.getElementById('popTitle').textContent = info.title;
      document.getElementById('popSub').textContent   = info.sub;
      document.getElementById('progBar').style.width  = info.prog + '%';
      const sl = document.getElementById('statusLine');
      sl.textContent = 'State: ' + s.state;
      sl.className   = 'status-line ' + info.cls;

      const btn = document.getElementById('scanBtn');
      // Reset to default enabled state; override below if needed
      btn.disabled = false;

      if (s.state === 'idle') {
        btn.textContent = 'Place finger — scan 1';
        btn.onclick = () => fetch('/api/enroll/scan1').then(() => pollState());

      } else if (s.state === 'scan1_done') {
        // Scan 1 is done → button now triggers scan 2
        btn.textContent = 'Place finger — scan 2';
        btn.onclick = () => fetch('/api/enroll/scan2').then(() => pollState());

      } else if (s.state === 'scan2_done' || s.state === 'processing' || s.state === 'storing') {
        // Fully automatic from here — no user button press needed
        btn.textContent = 'Processing...';
        btn.disabled = true;

      } else if (s.state === 'failed') {
        btn.textContent = 'Retry';
        btn.onclick = () => fetch('/api/enroll/reset').then(() => { pollState(); });

      } else {
        btn.textContent = '...';
        btn.disabled = true;
      }

      if (s.state === 'done') { setTimeout(closePopup, 2000); }
    }
    function openPopup(name) {
      if (!name) { alert('Enter a name first.'); return; }
      fetch('/api/enroll/start?name=' + encodeURIComponent(name))
        .then(() => {
          document.getElementById('overlay').style.display = 'flex';
          pollState();
        });
    }
    function closePopup() {
      fetch('/api/enroll/reset');
      document.getElementById('overlay').style.display = 'none';
      location.reload();
    }
  </script>
  )" + "</head><body>";

  page += "<h1>Enrollment System</h1>";
  page += "<div class='led-row'>";
  page += "<span class='dot' style='background:#4caf50'></span> Green ON &nbsp;";
  page += "<span class='dot' style='background:#f44336'></span> Red ON";
  page += "</div>";
  page += "<div class='card'>";
  page += "<h2>New Enrollment</h2>";
  if (msg.length()) {
    page += "<p style='color:" + String(isError?"#ef9a9a":"#a5d6a7") + "'>" + msg + "</p>";
  }
  page += "<input type='text' id='nameField' placeholder='Full name' /><br><br>";
  page += "<button class='primary' onclick='openPopup(document.getElementById(\"nameField\").value)'>Enroll fingerprint</button>";
  page += "</div>";

  // Enrolled users list
  page += "<div class='card'><h2>Enrolled Users (" + String(dbCount) + ")</h2>";
  if (dbCount == 0) {
    page += "<p style='color:#555'>No records yet.</p>";
  } else {
    for (int i = 0; i < dbCount; i++) {
      page += "<div class='db-row'><span>" + enrolledDB[i].name + "</span>"
              "<span class='uid'>" + enrolledDB[i].uniqueID + "</span></div>";
    }
  }
  page += "<br><a href='/api/db/clear' onclick=\"return confirm('Clear all records?')\" class='btn danger' style='font-size:0.8em'>Clear database</a>";
  page += "</div>";
  page += "<a href='/' class='btn' style='margin-top:1em'>← Home</a>";

  // Popup overlay (hidden by default)
  page += R"(
  <div class='overlay' id='overlay' style='display:none'>
    <div class='popup'>
      <h2 id='popTitle'>Idle</h2>
      <p id='popSub' style='font-size:0.85em;color:#aaa;margin-bottom:0.8em'>Waiting...</p>
      <svg class='finger-svg' width='60' height='76' viewBox='0 0 60 76' fill='none'>
        <rect x='18' y='0' width='24' height='48' rx='12' fill='#444'/>
        <rect x='10' y='24' width='12' height='36' rx='6' fill='#3a3a3a'/>
        <rect x='38' y='24' width='12' height='36' rx='6' fill='#3a3a3a'/>
        <rect x='4'  y='36' width='12' height='30' rx='6' fill='#333'/>
        <rect x='44' y='36' width='12' height='30' rx='6' fill='#333'/>
        <rect x='0'  y='50' width='60' height='26' rx='6' fill='#2a2a2a'/>
      </svg>
      <div class='progress'><div class='progress-bar' id='progBar' style='width:0'></div></div>
      <div class='status-line' id='statusLine'>State: idle</div>
      <div style='display:flex;gap:0.6em;margin-top:0.6em'>
        <button id='scanBtn' class='primary'>Place finger (scan 1)</button>
        <button onclick='closePopup()'>Cancel</button>
      </div>
    </div>
  </div>)";

  page += "<script>document.getElementById('scanBtn').onclick = () => fetch('/api/enroll/scan1').then(() => pollState());</script>";
  page += "</body></html>";
  server.send(200, "text/html", page);
}

// ──────────────────────────────────────────────────────────
// PAGE: AUTHORIZATION SYSTEM
// ──────────────────────────────────────────────────────────

void sendAuthorizationPage() {
  String page = "<!DOCTYPE html><html><head><title>Authorization</title>" + CSS_BASE + "</head><body>";
  page += "<h1>Authorization System</h1>";
  page += "<div class='led-row'><span class='dot' style='background:#ffeb3b'></span> Yellow ON</div>";
  page += "<div class='card'><h2>Verify Access</h2>";
  page += "<p>Scan fingerprint on the sensor. The system will match against enrolled users.</p>";
  page += "<p style='color:#666;font-size:0.8em'>Enrolled users: " + String(dbCount) + "</p>";

  // Simulate authorization result via URL param
  String result = server.hasArg("result") ? server.arg("result") : "";
  if (result == "ok") {
    page += "<p style='color:#a5d6a7'>✅ Access GRANTED — fingerprint matched.</p>";
  } else if (result == "fail") {
    page += "<p style='color:#ef9a9a'>❌ Access DENIED — no match found.</p>";
  }

  page += "<br><a href='/api/auth/simulate?match=1' class='btn enroll'>Simulate MATCH</a> ";
  page += "<a href='/api/auth/simulate?match=0' class='btn danger'>Simulate REJECT</a>";
  page += "</div>";
  page += "<a href='/' class='btn'>← Home</a> ";
  page += "<a href='/mode/1' class='btn enroll'>Switch to Enrollment</a>";
  page += "</body></html>";
  server.send(200, "text/html", page);
}

// ──────────────────────────────────────────────────────────
// ENROLLMENT STATE MACHINE — called by REST API handlers
// ──────────────────────────────────────────────────────────

String pendingName = "";

void enrollStart(const String& name) {
  pendingName = name;
  fp_resetTemplates();
  enrollState = ENROLL_IDLE;
  processingStartMs = 0;
  updateLeds();
  Serial.println("[Enroll] Started for: " + name);
}

void enrollScan1() {
  if (enrollState != ENROLL_IDLE) return;        // only valid from idle
  if (fp_captureTemplate1()) {
    enrollState = ENROLL_SCAN1_DONE;             // scan 1 done, waiting for scan 2
    updateLeds();
    Serial.println("[Enroll] Template 1 captured: " + fp_template1);
  }
}

void enrollScan2() {
  if (enrollState != ENROLL_SCAN1_DONE) return;  // only valid after scan 1
  if (fp_captureTemplate2()) {
    enrollState = ENROLL_SCAN2_DONE;             // scan 2 done, processing auto-starts
    processingStartMs = millis();
    updateLeds();
    Serial.println("[Enroll] Template 2 captured: " + fp_template2);
  }
}

// Called from loop() — drives automatic processing after scan 2
void enrollProcessLoop() {
  if (enrollState == ENROLL_SCAN2_DONE) {
    unsigned long elapsed = millis() - processingStartMs;
    if (elapsed > PROCESSING_TIMEOUT_MS) {
      enrollState = ENROLL_FAILED;
      updateLeds();
      Serial.println("[Enroll] FAILED — processing timeout");
      return;
    }
    if (elapsed > 1500) {
      enrollState = ENROLL_PROCESSING;
      updateLeds();
    }
  }
  if (enrollState == ENROLL_PROCESSING) {
    unsigned long elapsed = millis() - processingStartMs;
    if (elapsed > 3000) {
      String uid = fp_combineToUID();
      if (uid.isEmpty()) {
        enrollState = ENROLL_FAILED;
        updateLeds();
        Serial.println("[Enroll] FAILED — UID generation error");
        return;
      }
      enrollState = ENROLL_STORING;
      updateLeds();
      EnrolledUser u;
      u.name = pendingName;
      u.uniqueID = uid;
      u.enrolledAt = millis();
      if (enrollDB_save(u)) {
        enrollState = ENROLL_DONE;
        updateLeds();
        Serial.println("[Enroll] DONE — " + u.name + " → " + u.uniqueID);
      } else {
        enrollState = ENROLL_FAILED;
        updateLeds();
        Serial.println("[Enroll] FAILED — database full");
      }
    }
  }
}

void enrollReset() {
  fp_resetTemplates();
  pendingName = "";
  enrollState = ENROLL_IDLE;
  updateLeds();
}

String enrollStateString() {
  switch (enrollState) {
    case ENROLL_IDLE:       return "idle";
    case ENROLL_SCAN1_DONE: return "scan1_done";  // JS reads this → shows scan 2 button
    case ENROLL_SCAN2_DONE: return "scan2_done";  // JS reads this → shows "Processing..." disabled
    case ENROLL_PROCESSING: return "processing";
    case ENROLL_STORING:    return "storing";
    case ENROLL_DONE:       return "done";
    case ENROLL_FAILED:     return "failed";
  }
  return "unknown";
}

// ──────────────────────────────────────────────────────────
// SETUP
// ──────────────────────────────────────────────────────────

void setup() {
  Serial.begin(115200);
  pinMode(LED_GREEN,  OUTPUT);
  pinMode(LED_RED,    OUTPUT);
  pinMode(LED_YELLOW, OUTPUT);
  ledsOff();

  WiFi.begin(WIFI_SSID, WIFI_PASSWORD, WIFI_CHANNEL);
  Serial.print("Connecting to WiFi");
  while (WiFi.status() != WL_CONNECTED) { delay(100); Serial.print("."); }
  Serial.println(" Connected! IP: " + WiFi.localIP().toString());

  // ── Page routes ─────────────────────────────────────────
  server.on("/", sendHomePage);

  server.on(UriBraces("/mode/{}"), []() {
    int m = server.pathArg(0).toInt();
    if (m == 1 || m == 2) {
      currentMode = m;
      enrollReset();
      updateLeds();
      Serial.println("[Mode] → " + String(m == 1 ? "Enrollment" : "Authorization"));
    }
    if (currentMode == 1) sendEnrollmentPage();
    else if (currentMode == 2) sendAuthorizationPage();
    else sendHomePage();
  });

  // ── Enrollment REST API ──────────────────────────────────
  // These endpoints are called by the JS in the enrollment page.
  // Swap fetch() calls in the JS with real backend URLs later.

  server.on("/api/enroll/start", []() {
    String name = server.arg("name");
    if (name.isEmpty()) { server.send(400, "text/plain", "name required"); return; }
    enrollStart(name);
    server.send(200, "application/json", "{\"ok\":true}");
  });

  server.on("/api/enroll/scan1", []() {
    enrollScan1();
    server.send(200, "application/json",
      "{\"state\":\"" + enrollStateString() + "\"}");
  });

  server.on("/api/enroll/scan2", []() {
    enrollScan2();
    server.send(200, "application/json",
      "{\"state\":\"" + enrollStateString() + "\"}");
  });

  server.on("/api/enroll/state", []() {
    server.send(200, "application/json",
      "{\"state\":\"" + enrollStateString() + "\",\"name\":\"" + pendingName + "\"}");
  });

  server.on("/api/enroll/reset", []() {
    enrollReset();
    server.send(200, "application/json", "{\"ok\":true}");
  });

  // ── Database API ─────────────────────────────────────────
  server.on("/api/users", []() {
    server.send(200, "application/json", enrollDB_toJSON());
  });

  server.on("/api/db/clear", []() {
    enrollDB_clear();
    server.sendHeader("Location", "/mode/1");
    server.send(302);
  });

  // ── Authorization REST API ───────────────────────────────
  server.on("/api/auth/simulate", []() {
    bool match = server.arg("match") == "1";
    if (match) {
      ledSet(1,0,1); // G + Y on → granted
      delay(200);
    } else {
      ledSet(0,1,0); // R flash → denied
      delay(200);
      updateLeds();
    }
    server.sendHeader("Location", "/mode/2?result=" + String(match ? "ok" : "fail"));
    server.send(302);
  });

  server.begin();
  currentMode = 1; // start in enrollment mode
  updateLeds();
  Serial.println("[HTTP] Server started — http://localhost:8180");
}

// ──────────────────────────────────────────────────────────
// LOOP
// ──────────────────────────────────────────────────────────

void loop() {
  server.handleClient();
  enrollProcessLoop();   // drive the async state machine
  handleBlinkLeds();     // drive blink states for processing/failed
  delay(2);
}
